apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - platform/mysql
  - platform/phpmyadmin
  - platform/kafka
  - services/gateway-service
  - services/menu-service
  - services/order-service
  - services/payment-service
