apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-service-config
data:
  PAYMENT_DB_NAME: "restaurant_payment"
  PAYMENT_DB_URL: "jdbc:mysql://mysql:3306/restaurant_payment"
  PAYMENT_EVENTS_TOPIC: "payment.events"
  PAYMENT_CONSUMER_GROUP: "payment-service"
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  PAYMENT_MOCK_MODE: "true"
