apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: gateway-service
          image: docker.io/khcodenet1008/gateway-service:dev
          envFrom:
            - configMapRef:
                name: gateway-service-config
          ports:
            - containerPort: 8080
