apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/platform/mysql
  - ../base/platform/kafka
  - ../base/platform/istio
  - ../base/services/gateway-service
  - ../base/services/menu-service
  - ../base/services/order-service
  - ../base/services/payment-service
