apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: order-service
          image: docker.io/khcodenet1008/order-service:dev
          envFrom:
            - configMapRef:
                name: order-service-config
          ports:
            - containerPort: 8080
