apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: menu-service
  template:
    metadata:
      labels:
        app: menu-service
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: menu-service
          image: docker.io/khcodenet1008/menu-service:dev
          envFrom:
            - configMapRef:
                name: menu-service-config
          ports:
            - containerPort: 8080
